language: cpp

os: linux
dist: trusty
sudo: false

compiler: clang
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
      - llvm-toolchain-trusty-5.0
    packages:
      - g++-7 # we need this one for the libstdc++.
      - clang-5.0
      - ninja-build
      - python
      - python-pip
      - python3
      - python3-pip
      - libboost-python-dev

before_install:
  - pip2 install --user setuptools nose2
  - pip3 install --user setuptools nose2

script:
  - make check

notifications:
  email: false
