#pragma push_macro("check")
#undef check

#define CARLALIB_INCLUDED_FROM_UE4

#ifndef BOOST_ERROR_CODE_HEADER_ONLY
#  define BOOST_ERROR_CODE_HEADER_ONLY
#endif // BOOST_ERROR_CODE_HEADER_ONLY

#ifndef BOOST_COROUTINES_NO_DEPRECATION_WARNING
#  define BOOST_COROUTINES_NO_DEPRECATION_WARNING
#endif // BOOST_COROUTINES_NO_DEPRECATION_WARNING
