# Here CURDIR is assumed to be the root folder of the project.

CARLA_ROOT_FOLDER=${CURDIR}
CARLA_BUILD_FOLDER=${CURDIR}/Build
CARLA_BUILD_TOOLS_FOLDER=${CURDIR}/Util/BuildTools

CARLALIB_ROOT_FOLDER=${CURDIR}/CarlaLib
CARLALIB_BUILD_SERVER_FOLDER=${CARLA_BUILD_FOLDER}/carlalib-server-build
CARLALIB_BUILD_CLIENT_FOLDER=${CARLA_BUILD_FOLDER}/carlalib-client-build
CARLALIB_INSTALL_SERVER_FOLDER=${CURDIR}/Install/CarlaLib_Server
CARLALIB_INSTALL_CLIENT_FOLDER=${CURDIR}/Install/CarlaLib_Client

CARLAUE4_ROOT_FOLDER=${CURDIR}/Unreal/CarlaUE4
CARLAUE4_PLUGIN_ROOT_FOLDER=${CURDIR}/Unreal/CarlaUE4/Plugins/Carla
CARLAUE4_PLUGIN_DEPS_FOLDER=${CARLAUE4_PLUGIN_ROOT_FOLDER}/CarlaDependencies

CARLA_PYTHONAPI_ROOT_FOLDER=${CURDIR}/PythonAPI
CARLA_PYTHONAPI_DEPS_FOLDER=${CARLA_PYTHONAPI_ROOT_FOLDER}/dependencies

LIBSTDCPP_TOOLCHAIN_FILE=${CARLA_BUILD_FOLDER}/LibStdCppToolChain.cmake
LIBCPP_TOOLCHAIN_FILE=${CARLA_BUILD_FOLDER}/LibCppToolChain.cmake
CMAKE_CONFIG_FILE=${CARLA_BUILD_FOLDER}/CMakeLists.txt.in
