# Here CURDIR is assumed to be the root folder of the project.

CARLA_ROOT_FOLDER=${CURDIR}
CARLA_BUILD_FOLDER=${CURDIR}/Build
CARLA_BUILD_TOOLS_FOLDER=${CURDIR}/Util/BuildTools

CARLALIB_ROOT_FOLDER=${CURDIR}/CarlaLib
CARLALIB_BUILD_FOLDER=${CARLA_BUILD_FOLDER}/carlalib-build
CARLALIB_INSTALL_FOLDER=${CURDIR}/Install/CarlaLib

LIBCPP_TOOLCHAIN_FILE=${CARLA_BUILD_FOLDER}/LibCppToolChain.cmake
CMAKE_CONFIG_FILE=${CARLA_BUILD_FOLDER}/CMakeLists.txt.in
